CREATE TABLE events (
    dateTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    eventName VARCHAR(100) NOT NULL,
    eventDescription TEXT NOT NULL,
    eventAuthor VARCHAR(50) NOT NULL,
    eventType VARCHAR(50) NOT NULL,
    eventDateTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    eventImage VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `events` (`dateTime`, `id`, `eventName`, `eventDescription`, `eventAuthor`, `eventType`, `eventDateTime`, `eventImage`) VALUES (current_timestamp(), NULL, 'Operation MilSim Community 1', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis voluptatibus, doloribus nemo beatae blanditiis, tempore harum cum adipisci officia nesciunt nihil eius hic asperiores aliquid architecto facere, aspernatur cumque aliquam?', 'BentsuKun', 'Mission Day', '2025-03-09 20:30:00', 'https://tmr.cthcloud.com/IMAGES/image_slide/img_01.webp');
INSERT INTO `events` (`dateTime`, `id`, `eventName`, `eventDescription`, `eventAuthor`, `eventType`, `eventDateTime`, `eventImage`) VALUES (current_timestamp(), NULL, 'Operation MilSim Community 2', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis voluptatibus, doloribus nemo beatae blanditiis, tempore harum cum adipisci officia nesciunt nihil eius hic asperiores aliquid architecto facere, aspernatur cumque aliquam?', 'BentsuKun', 'Event', '2025-03-15 20:30:00', 'https://tmr.cthcloud.com/IMAGES/image_slide/img_02.webp');
INSERT INTO `events` (`dateTime`, `id`, `eventName`, `eventDescription`, `eventAuthor`, `eventType`, `eventDateTime`, `eventImage`) VALUES (current_timestamp(), NULL, 'Operation MilSim Community 3', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis voluptatibus, doloribus nemo beatae blanditiis, tempore harum cum adipisci officia nesciunt nihil eius hic asperiores aliquid architecto facere, aspernatur cumque aliquam?', 'BentsuKun', 'Training', '2025-03-16 20:30:00', 'https://tmr.cthcloud.com/IMAGES/image_slide/img_03.webp');
INSERT INTO `events` (`dateTime`, `id`, `eventName`, `eventDescription`, `eventAuthor`, `eventType`, `eventDateTime`, `eventImage`) VALUES (current_timestamp(), NULL, 'Operation MilSim Community 4', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis voluptatibus, doloribus nemo beatae blanditiis, tempore harum cum adipisci officia nesciunt nihil eius hic asperiores aliquid architecto facere, aspernatur cumque aliquam?', 'BentsuKun', 'Mission Day', '2025-03-22 20:30:00', 'https://tmr.cthcloud.com/IMAGES/image_slide/img_04.webp');
INSERT INTO `events` (`dateTime`, `id`, `eventName`, `eventDescription`, `eventAuthor`, `eventType`, `eventDateTime`, `eventImage`) VALUES (current_timestamp(), NULL, 'Operation MilSim Community 5', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis voluptatibus, doloribus nemo beatae blanditiis, tempore harum cum adipisci officia nesciunt nihil eius hic asperiores aliquid architecto facere, aspernatur cumque aliquam?', 'BentsuKun', 'Event', '2025-03-23 20:30:00', 'https://tmr.cthcloud.com/IMAGES/image_slide/img_05.webp');
INSERT INTO `events` (`dateTime`, `id`, `eventName`, `eventDescription`, `eventAuthor`, `eventType`, `eventDateTime`, `eventImage`) VALUES (current_timestamp(), NULL, 'Operation MilSim Community 6', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis voluptatibus, doloribus nemo beatae blanditiis, tempore harum cum adipisci officia nesciunt nihil eius hic asperiores aliquid architecto facere, aspernatur cumque aliquam?', 'BentsuKun', 'Training', '2025-03-29 20:30:00', 'https://tmr.cthcloud.com/IMAGES/image_slide/img_06.webp');
INSERT INTO `events` (`dateTime`, `id`, `eventName`, `eventDescription`, `eventAuthor`, `eventType`, `eventDateTime`, `eventImage`) VALUES (current_timestamp(), NULL, 'Operation MilSim Community 7', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis voluptatibus, doloribus nemo beatae blanditiis, tempore harum cum adipisci officia nesciunt nihil eius hic asperiores aliquid architecto facere, aspernatur cumque aliquam?', 'BentsuKun', 'Mission Day', '2025-03-30 20:30:00', 'https://tmr.cthcloud.com/IMAGES/image_slide/img_07.webp');
INSERT INTO `events` (`dateTime`, `id`, `eventName`, `eventDescription`, `eventAuthor`, `eventType`, `eventDateTime`, `eventImage`) VALUES (current_timestamp(), NULL, 'Operation MilSim Community 8', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis voluptatibus, doloribus nemo beatae blanditiis, tempore harum cum adipisci officia nesciunt nihil eius hic asperiores aliquid architecto facere, aspernatur cumque aliquam?', 'BentsuKun', 'Event', '2025-04-05 20:30:00', 'https://tmr.cthcloud.com/IMAGES/image_slide/img_08.webp');
INSERT INTO `events` (`dateTime`, `id`, `eventName`, `eventDescription`, `eventAuthor`, `eventType`, `eventDateTime`, `eventImage`) VALUES (current_timestamp(), NULL, 'Operation MilSim Community 9', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis voluptatibus, doloribus nemo beatae blanditiis, tempore harum cum adipisci officia nesciunt nihil eius hic asperiores aliquid architecto facere, aspernatur cumque aliquam?', 'BentsuKun', 'Training', '2025-04-06 20:30:00', 'https://tmr.cthcloud.com/IMAGES/image_slide/img_09.webp');