CREATE TABLE menu (
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    enName VARCHAR(50) NOT NULL,
    thName VARCHAR(50) NOT NULL,
    href VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;